#!/usr/bin/with-contenv bash
# shellcheck shell=bash

RECIPES_DIRECTORY="/recipes"
mkdir -p "$RECIPES_DIRECTORY"

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    lsiown -R abc:abc \
        /config
    lsiown abc:abc \
        "$RECIPES_DIRECTORY"
fi